apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ukpktest.statistic" . }}-job
  labels:
{{/*    sidecar.istio.io/inject: "false"*/}}
   {{- include "ukpktest.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed,hook-succeeded
{{/*    sidecar.istio.io/inject: "false"*/}}
spec:
  backoffLimit: 100
  template:
    metadata:
      name: {{ include "ukpktest.fullname" . }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: post-install-job
          image: {{.Values.statisticService.image.repository}}
          imagePullPolicy: {{.Values.statisticService.image.pullPolicy}}
          env:
          {{- range $key, $value := .Values.statisticService.env }}
            - name: {{ $value.name }}
              valueFrom:
                secretKeyRef:
                  key: {{ $value.key }}
                  name: {{- include "ukpktest.secret" $ | indent 4 }}
          {{- end }}
          command:
            - sh
            - "-c"
            - {{ printf "mycli %s -e \"create database if not exists \\`%s\\`\" && php /tmp/app/bin/console doctrine:migrations:migrate --quiet" ( printf (include "db.url" .) "" ) .Values.statisticService.database }}
