apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ukpktest.assets" . }}
  labels:
    name: {{ include "ukpktest.assets" . }}
    {{- include "ukpktest.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 0 # Default to 10 if not specified
  selector:
    matchLabels:
      name: {{ include "ukpktest.assets" . }}
      {{- include "ukpktest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        name: {{ include "ukpktest.assets" . }}
        {{- include "ukpktest.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ukpktest.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
                  {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.assets.image.repository }}:{{ .Values.assets.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.assets.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
                  {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.assets.develop.enabled }}
          volumeMounts:
            - name: {{ template "ukpktest.fullname" . }}-assets-assets
              mountPath: /var/www/assets
          {{ end }}
      volumes:
        {{- if .Values.assets.develop.enabled }}
        - name: {{ template "ukpktest.fullname" . }}-assets-assets
          hostPath:
            path: {{.Values.assets.develop.pwd}}
        {{ end }}
{{/*      {{- if not .Values.assets.develop.enabled }}*/}}
{{/*      initContainers:*/}}
{{/*        - name: {{ template "ukpktest.fullname" . }}-assets-assets*/}}
{{/*          image: "{{ .Values.assets.image.repository }}:{{ .Values.assets.image.tag | default .Chart.AppVersion }}"*/}}
{{/*          imagePullPolicy: {{ .Values.assets.image.pullPolicy }}*/}}
{{/*          command: ['sh', '-c', "cp -rT /tmp/assets /var/www/assets"]*/}}
{{/*          volumeMounts:*/}}
{{/*            - name: {{ template "ukpktest.fullname" . }}-assets-assets*/}}
{{/*              mountPath: /var/www/assets/*/}}
{{/*      {{ end }}*/}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}