apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ukpktest.fullname" . }}-grafana
spec:
  rules:
    - host: grafana.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "ukpktest.fullname" . }}-grafana
                port:
                  number: 80