apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ukpktest.secret" . }}
  labels:
    app: {{ template "ukpktest.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  MAIN_DATABASE_URL: {{ printf (include "db.url" .) .Values.mainService.database  | b64enc | quote}}
{{/*  STATISTIC_DATABASE_URL: {{ printf (include "db.url" .) .Values.statisticService.database  | b64enc | quote}}*/}}
  AUTH_DATABASE_URL: {{ printf (include "db.url" .) .Values.authService.database  | b64enc | quote}}
  KAFKA_URL: {{ printf "%s:%s"  .Values.kafka.fullnameOverride  (.Values.kafka.containerPorts.client | toString)  | b64enc | quote }}
  ZOOKEEPER_URL: {{ printf "%s:%s"  .Values.kafka.zookeeper.fullnameOverride  (.Values.kafka.zookeeper.containerPorts.client | toString)  | b64enc | quote }}