{{/*apiVersion: traefik.containo.us/v1alpha1*/}}
{{/*kind: IngressRoute*/}}
{{/*metadata:*/}}
{{/*  name: traefik-dashboard*/}}
{{/*spec:*/}}
{{/*  routes:*/}}

{{/*    - match: PathPrefix(`/`)*/}}
{{/*      kind: Rule*/}}
{{/*      services:*/}}
{{/*        - name: api@internal*/}}
{{/*          kind: TraefikService*/}}